---
- hosts: server
  become: true
  vars:
    nginx_install_dir: "/tmp/{{ nginx_version }}"
    nginx_sbin_path: "/usr/sbin/nginx"
    nginx_conf_path: "/etc/nginx/nginx.conf"
    nginx_custom_modules: "--with-http_auth_request_module"
    nginx_listen_port: 10001

  tasks:
    - name: Делаем директорию под страничку сайта
      become: true
      file:
        path: /opt/www
        state: directory
        owner: root
        mode: 0777
    - name: Устанавливаем epel-репозиторий
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages
    - name: Устанавливаем необходимые и вспомогательные пакеты через yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - yum-utils
        - setools
        - policycoreutils
        - policycoreutils-python
        - setroubleshoot
        - nginx
    - name: Установка разрешения setsebool -P nis_enabled 1
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes       
    - name: Создаем конфигурацию nginx используя шаблон jinja2
      template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
      tags:
        - nginx-configuration
    - name: копируем страничку index.html на место
      copy:
        src: index.html
        dest: /opt/www/index.html
        owner: root
        group: root
        mode: '0777'
      become: true
    - name: enable service nginx
      systemd:
        name: nginx
        enabled: yes
        masked: no      
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted


