---
- hosts: server
  become: true
  vars:
    nginx_install_dir: "/tmp/{{ nginx_version }}"
    nginx_sbin_path: "/usr/sbin/nginx"
    nginx_conf_path: "/etc/nginx/nginx.conf"
    nginx_custom_modules: "--with-http_auth_request_module"
    nginx_listen_port: 5000

  tasks:
    - name: Делаем директорию под страничку сайта
      become: true
      file:
        path: /opt/www
        state: directory
        owner: root
        mode: 0777
    - name: Устанавливаем epel-репозиторий
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages
    - name: Устанавливаем необходимые и вспомогательные пакеты через yum
      become: true
      yum:
        name: "{{item}}"
        state: present
      loop:
        - mc
        - nano
        - yum-utils
        - setools
        - policycoreutils
        - policycoreutils-python
        - setroubleshoot
        - nginx

#    - name: Transfer the script
#      copy: src=script.sh dest=/home/vagrant mode=0777

    - name: Остановим nginx
      service: 
        name: nginx 
        state: stopped
        
    - name: Отключим nginx
      systemd:
        name: nginx
        enabled: yes
        masked: no 


    - name: Создаем конфигурацию nginx используя шаблон jinja2
      template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
      tags:
        - nginx-configuration

    - name: копируем страничку index.html на место
      copy:
        src: index.html
        dest: /opt/www/index.html
        owner: root
        group: root
        mode: '0777'
      become: true

    - name: Включаем сервис nginx
      systemd:
        name: nginx
        enabled: yes
        masked: no      

############ тут придется руками
#    - name: Команда 1
#      shell: ausearch -c 'nginx' --raw | audit2allow -M nginx-custom-port

#    - name: Команда 2
#      shell: semodule -i nginx-custom-port.pp


    - name: Делаем рестарт nginx
      systemd:
        name: nginx
        state: restarted


