---
- hosts: all # part running on all hosts
  become: true
  tasks:
  - name: install packages # переведём синтаксис yum из deprecated
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - mc # для удобства работы
      - nano  # для удобства работы
      - bind-chroot # добавить возможность chroot
      - bind
      - bind-utils
      - ntp
      - policycoreutils-python
      - setools
      - setroubleshoot-server

- hosts: ns01 # server ns01 provision
  become: true
  tasks:
### делаем операции под chroot
  - name: Делаем операции под chroot. Остановить сервис named
    systemd:
      name: named
      state: stopped
      enabled: no

  - name: Делаем операции под chroot. Копируем
    command: /usr/bin/cp /var/named/{{ item }} /var/named/chroot/var/named
    with_items:
      - "named.localhost"
      - "named.loopback"
      - "named.ca"
      - "named.empty"

  - name: Делаем операции под chroot. Ставим разрешения на файлы. 
    file:
      path: /var/named/chroot/var/named/{{ item }}
      owner: named
      group: named
      mode: 0640
    with_items:
      - "named.localhost"
      - "named.loopback"
      - "named.ca"
      - "named.empty"    

  - name: Делаем операции под chroot. Создаем директорию
    file:
      path: /var/named/chroot/var/named/data
      owner: named
      group: named
      state: directory
      mode: '0760'  
  
  - name: copy named.conf - Меняем адрес с /etc/ на /var/
    copy:
      src: files/ns01/named.conf
      dest: /var/named/chroot/etc/named.conf
      owner: root
      group: named
      mode: 0640


  - name: copy master zone dns.lab - Меняем адрес с /etc/ на /var/
    copy:
      src: "{{ item }}"
      dest: /var/named/chroot/etc/named/
      owner: root
      group: named
      mode: 0660
    with_fileglob:
      - files/ns01/named.dns*

  - name: copy dynamic zone ddns.lab  - Меняем адрес с /etc/ на /var/
    copy:
      src: files/ns01/named.ddns.lab
      dest: /var/named/chroot/var/named/dynamic/
      owner: named
      group: named
      mode: 0660

  - name: copy dynamic zone ddns.lab.view1 - Меняем адрес с /etc/ на /var/
    copy:
      src: files/ns01/named.ddns.lab.view1
      dest: /var/named/chroot/var/named/dynamic/
      owner: named
      group: named
      mode: 0660

  - name: copy master zone newdns.lab - Меняем адрес с /etc/ на /var/
    copy:
      src: files/ns01/named.newdns.lab
      dest: /var/named/chroot/etc/named/
      owner: root
      group: named
      mode: 0660

  - name: copy rev zones - Меняем адрес с /etc/ на /var/
    copy:
      src: files/ns01/named.50.168.192.rev
      dest: /var/named/chroot/etc/named/
      owner: root
      group: named
      mode: 0660

  - name: copy resolv.conf to server - Меняем адрес с /etc/ на /var/
    copy:
      src: files/ns01/resolv.conf
      dest: /var/named/chroot/etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: copy transferkey to server - Меняем адрес с /etc/ на /var/
    copy:
      src: files/named.zonetransfer.key.special
      dest: /var/named/chroot/etc/named.zonetransfer.key
      owner: root
      group: named
      mode: 0644

  - name: set permissions - Меняем адрес с /etc/ на /var/
    file:
      path: /var/named/chroot/etc/named
      owner: root
      group: named
      mode: 0670

  - name: set permissions - Меняем адрес с /etc/ на /var/
    file:
      path: /var/named/chroot/var/named/dynamic
      owner: root
      group: named
      mode: 0670

  - name: setsebool -P named_write_master_zones 1
    seboolean:
      name: named_write_master_zones
      state: yes
      persistent: yes

  - name: ensure named is running and enabled
    systemd:
      name: named-chroot
      state: restarted
      enabled: yes

- hosts: ns02 # server ns02 provision
  become: true
  tasks:
  - name: copy named.conf
    copy:
      src: files/ns02/named.conf
      dest: /etc/named.conf
      owner: root
      group: named
      mode: 0640

### закончили
  - name: copy resolv.conf to the server
    copy:
      src: files/ns02/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: copy transferkey to server
    copy:
      src: files/named.zonetransfer.key.special
      dest: /etc/named.zonetransfer.key
      owner: root
      group: named
      mode: 0644

  - name: set /etc/named permissions
    file:
      path: /etc/named
      owner: root
      group: named
      mode: 0670

#  - name: set /etc/named/dynamic permissions
#    file:
#      path: /etc/named/dynamic
#      owner: root
#      group: named
#      mode: 0670

  - name: ensure named is running and enabled
    systemd:
      name: named
      state: restarted
      enabled: yes

- hosts: client # first client provision
  become: true
  tasks:
  - name: copy resolv.conf to the client
    copy:
      src: files/client/resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: 0644

  - name: copy rndc conf file
    copy:
      src: files/client/rndc.conf
      dest: /home/vagrant/rndc.conf
      owner: vagrant
      group: vagrant
      mode: 0644

  - name: copy motd to the client
    copy:
      src: files/client/motd
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644

  - name: copy transferkey to client
    copy:
      src: files/named.zonetransfer.key.special
      dest: /etc/named.zonetransfer.key
      owner: root
      group: named
      mode: 0644